<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <OutputPath>..\Bin\BenchmarkTest</OutputPath>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <IsPackable>false</IsPackable>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.14.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NewLife.Siemens\NewLife.Siemens.csproj" />
  </ItemGroup>

</Project>
